### ISSUE TITLE
Cannot create android platform with this plugin (Unable to graft xml at selector "/manifest/uses-sdk")

### ISSUE THREAD

**Issue by Zrny** [regulaforensics/cordova-plugin-documentreader#6]
```
Microsoft Windows [Version 10.0.17763.864]
(c) 2018 Microsoft Corporation. Všechna práva vyhrazena.

C:\WINDOWS\system32>cd test
Systém nemůže nalézt uvedenou cestu.

C:\WINDOWS\system32>cd c:/

c:\>mkdir test

c:\>cd test

c:\test>cordova create mytest
Creating a new cordova project.

c:\test>cd mytest

c:\test\mytest>cordova plugin add cordova-plugin-documentreader
Adding cordova-plugin-documentreader to package.json

c:\test\mytest>cordova platform add android
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
Installing "cordova-plugin-documentreader" for android
Failed to install 'cordova-plugin-documentreader': Error: Unable to graft xml at selector "/manifest/uses-sdk" from "c:\test\mytest\platforms\android\app\src\main\AndroidManifest.xml" during config install
    at ConfigFile_graft_child [as graft_child] (c:\test\mytest\node_modules\cordova-common\src\ConfigChanges\ConfigFile.js:120:19)
    at PlatformMunger_apply_file_munge [as apply_file_munge] (c:\test\mytest\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:81:34)
    at munge_helper (c:\test\mytest\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:238:14)
    at PlatformMunger.add_plugin_changes (c:\test\mytest\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:159:12)
    at c:\test\mytest\node_modules\cordova-common\src\PluginManager.js:123:29
    at _fulfilled (c:\test\mytest\node_modules\q\q.js:854:54)
    at c:\test\mytest\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (c:\test\mytest\node_modules\q\q.js:816:13)
    at c:\test\mytest\node_modules\q\q.js:877:14
    at runSingle (c:\test\mytest\node_modules\q\q.js:137:13)
Unable to graft xml at selector "/manifest/uses-sdk" from "c:\test\mytest\platforms\android\app\src\main\AndroidManifest.xml" during config install

c:\test\mytest>
```

**Comment by vyakimchik** [comment]
Hi. Try to use the following project with the latest Beta SDK: https://github.com/regulaforensics/DocumentReader-Cordova-Plugin/tree/Beta as this project is no longer supported.

**Comment by Zrny** [comment]
Ah, you should write warning to the head of readme for future wanderers :) thank you, ill try it out
